### ISSUE TITLE
Отображение эликсиров.

### ISSUE THREAD

**Issue by kupetsky** [Zippelin/LA_Armory_Enchancer#2]
Похоже, с вводом системы высшей закалки сломалось отображение эликсиров на снаряге, где есть высшая закалка. Не критично в целом, но было бы неполохо, если есть возможность починить.

**Comment by Zippelin** [comment]
Привет, в курсе про проблему, после выхода Т4 буду разбираться, большой шанс, что с новым аддом поедет все.
